Remove socialImage of about and projects page temporarily due to type issue
To be research due to the following type issue:

GraphQLError: Field "socialImage" of type "File" must have a selection of subfields. Di
  d you mean "socialImage { ... }"?